AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  {"createdOn":"Mac","createdBy":"Amplify","createdWith":"12.10.1","stackType":"queue-SQS","metadata":{}}
Parameters:
  env:
    Type: String
Resources:
  PriceWatcherQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
      QueueName:
        Fn::Join:
          - ''
          - - priceWatcher-queue-
            - Ref: env
  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: PriceWatcherQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - SQS:DeleteMessage
              - SQS:GetQueueAttributes
            Resource:
              Fn::GetAtt:
                - PriceWatcherQueue
                - Arn
  PriceMessengerQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
      QueueName:
        Fn::Join:
          - ''
          - - priceMessenger-queue-
            - Ref: env
  PriceMessengerSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: PriceMessengerQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
              - SQS:DeleteMessage
              - SQS:GetQueueAttributes
            Resource:
              Fn::GetAtt:
                - PriceMessengerQueue
                - Arn
Outputs:
  QueueURL:
    Description: URL of the priceWatcher Queue
    Value:
      Ref: PriceWatcherQueue
  QueueARN:
    Description: ARN of the priceWatcher Queue
    Value:
      Fn::GetAtt:
        - PriceWatcherQueue
        - Arn
  QueueName:
    Description: Name new the priceWatcher Queue
    Value:
      Fn::GetAtt:
        - PriceWatcherQueue
        - QueueName
  PriceMessengerQueueURL:
    Description: URL of the priceMessenger Queue
    Value:
      Ref: PriceMessengerQueue
  PriceMessengerQueueARN:
    Description: ARN of the priceMessenger Queue
    Value:
      Fn::GetAtt:
        - PriceMessengerQueue
        - Arn
  PriceMessengerQueueName:
    Description: Name new the priceMessenger Queue
    Value:
      Fn::GetAtt:
        - PriceMessengerQueue
        - QueueName
